language: groovy
jdk:
- oraclejdk7
after_success:
- ./gradlew --stacktrace --debug  bintrayUpload -PbtIdentity="${btIdentity}" -PbtIDCreds="${btIDCreds}
  -PbuildId=${TRAVIS_BUILD_NUMBER}"
env:
  global:
  - secure: byG64EB1wICbr2xijrNJfNy1UFy6UWXlC9wfSTQ+85lgI+D4pQiRzHCctPesafqx33Ak62dSg6vQBal1iN8Pe9QZMyvqcF62FqqALontKQlIVC723bOzvRtidRSOXy09f+yGMZrs5EGPIkEbMYNIYBwD5AUa+rg9p31qsb8C6C4=
  - secure: R0ZTEPEGuK7GUXsaIEcQMGZjZ8FTXkXTGD97J3Z6bowBfkIZlIa5enTD8w+/cGBeYssKCmxyarPvT96m6YXxcCjSF68eNkTRju7HNwQZBaY3PcsUaXXZjNq3FOzoAHVvEZEcrFNH9LUBclg/CPYbYSpAYUZtdiWQaVRVFoYifQc=
