language: groovy
jdk:
- oraclejdk7
after_success:
- ./gradlew bintrayUpload -PbtIdentity="${btIdentity}" -PbtIDCreds="${btIDCreds}"
  -PbuildId="${TRAVIS_BUILD_NUMBER}"
env:
  global:
  - secure: YROmYduBO1ZXeffsSH56VqRwEakgK72VXM6CnyyTNvw11YWXM1BzcV2LNbQc+X1E3spAgNrWqcOz+YdK53VF+kC/IPXbbEJWVzYFYAHXaAmk+10tAFd0CPDqh1S7tdUGmwHsNp3QRJ3B3OrbjBckL5sX/+y2KZW4+todRthr6fo=
  - secure: D8x1tc9o3Vke+6eoE4m88LF8IHivAvh0hF3wPOvt8xnM35CkW3C4MN7WpQVG5MucCmKlf+W9qeBo5lEGNxSUx/mMuSmvo2YFgisrJIOlC3VCBVFFQCasfggCYp4sDdUZBvHSGf2Bipz6HotTUBmXvMfkbX51ZiP2haV4168RsjI=
