language: groovy
jdk:
- oraclejdk7
after_success:
- ./gradlew  bintrayUpload -PbtIdentity="${btIdentity}" -PbtIDCreds="${btIDCreds} -PbuildID=${TRAVIS_JOB_ID}"
env:
  global:
  - secure: IDYEPSpXn0GlZi8g4TWciVtrY5UYYqSzr7FMq7K3I+oQUlnW437L7dp+7ewuoUs7i53PAKj5njIJezlsqyYdUYTQ8HgS3eTvfW2sT+ucDFmnV5blsn1lh2LhfejI6H4pxHHvbDdVJkPM3/INZr+GO0/IqzTyFLDnTqa3wKnNKAE=
  - secure: ZWA7W3acEQNL8NoHSBIf1HZDIn6lX8v9wSARoiRMAPhtKIjtI/ebmutXzu7UN4D4l03S55hMN77n2+1XzVxxLCoCKTn67DkEC0vF+fKbOooUtZ7xChQGyvNjTDbAiBF0Rgq3B3WEQt1/pjk/PuZg61lLrFV0I80yoQDT/T7cCQo=
